{
 "title": "EII Video and Time Series Dashboard_my",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Input Image1",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "measurement_test",
     "query": "SELECT \"input_img_base64_string_0\" ,\"filename_0\" FROM \"autogen\".\"measurement_test2\" WHERE time >= now() - 1h\nORDER BY time DESC\nLIMIT 1\n",
     "select": [
      [
       { "params": [ "image_url" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Prediction1",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "measurement_test",
     "query": "SELECT \"predictions_base64_string_0\" ,\"toolwear_0\" FROM \"autogen\".\"measurement_test2\" WHERE time >= now() - 1h\nORDER BY time DESC\nLIMIT 1\n",
     "select": [
      [
       { "params": [ "image_url" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Superimpose image1",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "measurement_test",
     "query": "SELECT \"superimpose_base64_string_0\" ,\"model_0\" FROM \"autogen\".\"measurement_test2\" WHERE time >= now() - 1h\nORDER BY time DESC\nLIMIT 1\n",
     "select": [
      [
       { "params": [ "image_url" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Input Image2",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "measurement_test",
     "query": "SELECT \"input_img_base64_string_1\" ,\"filename_1\" FROM \"autogen\".\"measurement_test2\" WHERE time >= now() - 1h\nORDER BY time DESC\nLIMIT 1\n",
     "select": [
      [
       { "params": [ "image_url" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Prediction2",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "measurement_test",
     "query": "SELECT \"predictions_base64_string_1\" ,\"toolwear_1\" FROM \"autogen\".\"measurement_test2\" WHERE time >= now() - 1h\nORDER BY time DESC\nLIMIT 1\n",
     "select": [
      [
       { "params": [ "image_url" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Superimpose image2",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "measurement_test",
     "query": "SELECT \"superimpose_base64_string_1\" ,\"model_1\" FROM \"autogen\".\"measurement_test2\" WHERE time >= now() - 1h\nORDER BY time DESC\nLIMIT 1\n",
     "select": [
      [
       { "params": [ "image_url" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature Compensation ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "measurement_test",
     "query": "SELECT mean(\"GT\") ,mean(\"pred\")  FROM \"autogen\".\"measurement_test\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "GT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}